### ISSUE TITLE
Dijagrami aktivnosti

### ISSUE THREAD

**Issue by EmirKapic** [EmirKapic/TechHaven#1]
1. Scenario 5 pogrešna slika
2. Scenario 7 validacija podataka ( bez baza)
3. Svi oblačići da budu istog izgleda
4. Zamjeniti "slanje error poruke" sa nečim bolje definisam
5. Izbaciti riječ "baza" i "id"
6. Dosta dijagrama je ciklično

**Comment by ibecir** [comment]
Sada su diagrami uredu, kad otvorite issue nemojte ga vi zatvarati, nego cu ga ja zatvoriti i reci vam da merge branch
